-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 12:59:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema produblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema produblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `produblog` DEFAULT CHARACTER SET utf8 ;
USE `produblog` ;

-- -----------------------------------------------------
-- Table `produblog`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produblog`.`Users` ;

CREATE TABLE IF NOT EXISTS `produblog`.`Users` (
  `idUsers` INT NOT NULL,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `usertype` VARCHAR(32) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produblog`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produblog`.`Post` ;

CREATE TABLE IF NOT EXISTS `produblog`.`Post` (
  `idPost` INT NOT NULL,
  `postname` VARCHAR(64) NULL,
  `postcontent` VARCHAR(255) NULL,
  `Users_idUsers` INT NOT NULL,
  `File_ops` VARCHAR(255) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idPost`, `Users_idUsers`),
  INDEX `fk_Post_Users1_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_Post_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `produblog`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produblog`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produblog`.`Comment` ;

CREATE TABLE IF NOT EXISTS `produblog`.`Comment` (
  `idComment` INT NOT NULL,
  `commentcontent` VARCHAR(255) NULL,
  `Users_idUsers` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idComment`, `Users_idUsers`, `Post_idPost`),
  INDEX `fk_Comment_Users1_idx` (`Users_idUsers` ASC),
  INDEX `fk_Comment_Post1_idx` (`Post_idPost` ASC),
  CONSTRAINT `fk_Comment_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `produblog`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `produblog`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
